### ISSUE TITLE
Errors in 1. Python Basics directory

### ISSUE THREAD

**Issue by JasonNielsen** [Yanall-Boutros/ParticleSHAI#2]
It seems that `matplotlib` cannot be imported in `four_vec.py`

```
tf-docker /particleSHAI/Examples/1. Python Basics > python four_vec.py
Traceback (most recent call last):
  File "four_vec.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
```

Does some Python library path need to be set?

**Comment by Yanall-Boutros** [comment]
Executed as python3? I removed pip2 so that might be the issue. Example 9 should be  the current working folder also. 

From the docker file:

`RUN python3 -m pip install --user numpythia **matplotlib** pyjet tensorflow requests pandas scikit-hep scikit-learn uproot scipy pyhepmc-ng `

So it should be included. I'll look into the build later also.

Additionally, tensorflow renamed some modules... So there'll be some issues when executing `./python3 network.py`

**Comment by JasonNielsen** [comment]
It’s the same error for python2 and python3.

**Comment by Yanall-Boutros** [comment]
I will rebuild right now

**Comment by Yanall-Boutros** [comment]
Without rebuilding, matplotlib worked on my docker file. That seems suspicious, given the nature of a docker container. What is tf-docker? 

Append this to line 1 of the python script.

`#!/usr/bin/python3`

Then make the script executable

`$chmod +x four_vec.py`

And execute

`$./four_vec.py`

I suspect having bash directly go to that environment might fix the issue. I don't know why it wouldn't be the same on your system as on mine. Is your tag id `08d234953f3e`? Anyways I'll look into rebuilding.

**Comment by JasonNielsen** [comment]
Apparently, tf-docker is TensorFlow docker. I assumed that it was something that you had created.

**Comment by Yanall-Boutros** [comment]
Ah, that makes sense. My docker builds off that, I assume the name got inherited.

It's working on my end, and I'm not sure what I should change to make it work. You are pulling from yboutros/particlesh**ai** correct? maybe it's getting an older build from the obsolete yboutros/particlesh?

Otherwise, should we save this for our meeting tomorrow? I have some other issues, such as jet.userinfo being nonetype everywhere except for one function for some reason. I can get everything I need in that one function but it's kind of painful to look at spaghetti code. I need the jet.userinfo to count the number of bjets in an event.

**Comment by JasonNielsen** [comment]
Hi, Yanall,

I pulled again from yboutros/particleshai:initial, but I still could not import matplotlib.

I noticed that I could not import any of the packages that were installed on this line

/bin/sh -c python3 -m pip install --user numpythia matplotlib pyjet tensorflow requests pandas scikit-hep scikit-learn uproot scipy pyhepmc-ng

except for tensorflow. I could import numpy, which was installed by itself in the preceding command. Maybe that is a hint.

Regards,
Jason

**Comment by Yanall-Boutros** [comment]
Hello, Professor,

I rebuilt and pushed to yboutros/particleshai, hopefully reverting back to pip3 works (the old code was a work around that is no longer needed).

Thanks for identifying the troublesome line,

Thanks,
Yanall

**Comment by JasonNielsen** [comment]
Great, now it works. (At least I can import numpythia and matplotlib…)

Thanks!

**Comment by Yanall-Boutros** [comment]
Thanks for checking, I'll check the rest of the import statements. I'll close both these issues as well.
